Repository Prography-8th-team8/Cakk-AOS, pull requests merged in 2023-07, with the labels that each got.

#37 [Feat] 케이크 샵 상세 화면 블로그 리뷰 API 연동
  core/designsystem/src/main/res/values/strings.xml
  core/network/src/main/java/org/prography/network/CakkService.kt
  core/network/src/main/java/org/prography/network/api/dto/response/BlogPostResponse.kt
  core/network/src/main/java/org/prography/network/api/dto/response/StoreBlogResponse.kt
  data/src/main/java/org/prography/cakk/data/datasource/StoreRemoteSource.kt
  data/src/main/java/org/prography/cakk/data/repository/StoreRepositoryImpl.kt
  domain/src/main/java/org/prography/domain/model/store/BlogPostModel.kt
  domain/src/main/java/org/prography/domain/model/store/StoreBlogModel.kt
  domain/src/main/java/org/prography/domain/repository/StoreRepository.kt
  feature/home/src/main/java/org/prography/home/HomeUiSideEffect.kt
  feature/home/src/main/java/org/prography/home/HomeViewModel.kt
  feature/home/src/main/java/org/prography/home/detail/BlogReviewModel.kt
  feature/home/src/main/java/org/prography/home/detail/HomeDetailAction.kt
  feature/home/src/main/java/org/prography/home/detail/HomeDetailScreen.kt
  feature/home/src/main/java/org/prography/home/detail/HomeDetailSideEffect.kt
  feature/home/src/main/java/org/prography/home/detail/HomeDetailState.kt
  feature/home/src/main/java/org/prography/home/detail/HomeDetailViewModel.kt
Labels: Feature, Done, 원석

#40 [feat] #38 홈 화면의 바텀시트 스크롤 이슈 수정
  feature/home/src/main/java/org/prography/home/HomeScreen.kt
Labels: Bug, Done, 원석

#43 [Bug] 지역 변경 클릭 시 카메라 위치가 변경되지 않는 현상 수정
  app/src/main/java/org/prography/cakk/navigation/CakkNavigationGraph.kt
  core/utility/src/main/java/org/prography/utility/navigation/destination/CakkDestination.kt
  feature/home/src/main/java/org/prography/home/HomeScreen.kt
Labels: Bug, Done, 원석

#44 [Feat] 케이크샵 지역 재검색 개발
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  core/designsystem/src/main/java/org/prography/designsystem/ui/theme/Color.kt
  core/designsystem/src/main/res/drawable/ic_swap_white.xml
  core/network/src/main/java/org/prography/network/CakkService.kt
  core/network/src/main/java/org/prography/network/api/dto/response/BlogPostResponse.kt
  core/network/src/main/java/org/prography/network/api/dto/response/StoreBlogResponse.kt
  core/network/src/main/java/org/prography/network/api/dto/response/StoreReloadResponse.kt
  core/utility/src/main/java/org/prography/utility/mapper/StoreMapper.kt
  data/src/main/java/org/prography/cakk/data/datasource/StoreRemoteSource.kt
  data/src/main/java/org/prography/cakk/data/repository/StoreRepositoryImpl.kt
  domain/src/main/java/org/prography/domain/repository/StoreRepository.kt
  feature/home/src/main/java/org/prography/home/HomeScreen.kt
  feature/home/src/main/java/org/prography/home/HomeUiAction.kt
  feature/home/src/main/java/org/prography/home/HomeUiState.kt
  feature/home/src/main/java/org/prography/home/HomeViewModel.kt
Labels: Feature, Done, 원석

#45 [feat] 가게 필터링 구현
  app/src/main/java/org/prography/cakk/navigation/CakkNavigationGraph.kt
  core/designsystem/src/main/java/org/prography/designsystem/mapper/TypeColor.kt
  core/designsystem/src/main/java/org/prography/designsystem/mapper/TypeIcon.kt
  core/designsystem/src/main/java/org/prography/designsystem/ui/theme/Color.kt
  core/designsystem/src/main/java/org/prography/designsystem/ui/theme/Theme.kt
  core/designsystem/src/main/res/drawable/ic_character.xml
  core/designsystem/src/main/res/drawable/ic_close.xml
  core/designsystem/src/main/res/drawable/ic_figure.xml
  core/designsystem/src/main/res/drawable/ic_filter.xml
  core/designsystem/src/main/res/drawable/ic_flower.xml
  core/designsystem/src/main/res/drawable/ic_lettering.xml
  core/designsystem/src/main/res/drawable/ic_mealbox.xml
  core/designsystem/src/main/res/drawable/ic_photo.xml
  core/designsystem/src/main/res/drawable/ic_refresh.xml
  core/designsystem/src/main/res/drawable/ic_ricecake.xml
  core/designsystem/src/main/res/drawable/ic_solid.xml
  core/designsystem/src/main/res/drawable/ic_tiara.xml
  core/designsystem/src/main/res/values/strings.xml
  core/network/src/main/java/org/prography/network/CakkService.kt
  core/network/src/main/java/org/prography/network/api/dto/response/DistrictResponse.kt
  data/src/main/java/org/prography/cakk/data/datasource/StoreRemoteSource.kt
  data/src/main/java/org/prography/cakk/data/repository/StoreRepositoryImpl.kt
  domain/src/main/java/org/prography/domain/model/district/DistrictModel.kt
  domain/src/main/java/org/prography/domain/model/enums/DistrictType.kt
  domain/src/main/java/org/prography/domain/model/enums/StoreType.kt
  domain/src/main/java/org/prography/domain/repository/StoreRepository.kt
  feature/home/src/main/java/org/prography/home/HomeScreen.kt
  feature/home/src/main/java/org/prography/home/HomeUiAction.kt
  feature/home/src/main/java/org/prography/home/HomeUiState.kt
  feature/home/src/main/java/org/prography/home/HomeViewModel.kt
  feature/home/src/main/java/org/prography/home/detail/HomeDetailScreen.kt
Labels: Feature, Done, 준경

#49 [feat] 홈 화면 케이크 리스트 데이터 UI 변경
  core/base/src/main/java/org/prography/base/BaseViewModel.kt
  core/designsystem/build.gradle.kts
  core/designsystem/src/main/java/org/prography/designsystem/component/Store.kt
  core/designsystem/src/main/res/drawable/ic_heart.xml
  core/designsystem/src/main/res/drawable/ic_heart_sel.xml
  core/designsystem/src/main/res/values/strings.xml
  core/network/src/main/java/org/prography/network/CakkService.kt
  core/network/src/main/java/org/prography/network/api/dto/response/StoreReloadResponse.kt
  core/network/src/main/java/org/prography/network/api/dto/response/StoreResponse.kt
  core/network/src/main/java/org/prography/network/api/dto/response/StoreTypeResponse.kt
  data/src/main/java/org/prography/cakk/data/datasource/StoreRemoteSource.kt
  data/src/main/java/org/prography/cakk/data/repository/StoreRepositoryImpl.kt
  domain/src/main/java/org/prography/domain/model/store/StoreModel.kt
  domain/src/main/java/org/prography/domain/repository/StoreRepository.kt
  feature/home/src/main/java/org/prography/home/HomeScreen.kt
  feature/home/src/main/java/org/prography/home/HomeUiAction.kt
  feature/home/src/main/java/org/prography/home/HomeViewModel.kt
  feature/home/src/main/java/org/prography/home/detail/HomeDetailAction.kt
  feature/home/src/main/java/org/prography/home/detail/HomeDetailScreen.kt
  feature/home/src/main/java/org/prography/home/detail/HomeDetailViewModel.kt
  feature/onboarding/src/main/java/org/prography/onboarding/OnBoardingAction.kt
  feature/onboarding/src/main/java/org/prography/onboarding/OnBoardingScreen.kt
  feature/onboarding/src/main/java/org/prography/onboarding/OnBoardingSideEffect.kt
  feature/onboarding/src/main/java/org/prography/onboarding/OnBoardingViewModel.kt
  gradle/libs.versions.toml
Labels: Feature, Done, 원석

#53 [feat] 케이크샵 상세화면 디자인 변경
  app/src/main/java/org/prography/cakk/navigation/CakkNavigationGraph.kt
  core/designsystem/src/main/java/org/prography/designsystem/component/AppBar.kt
  core/designsystem/src/main/java/org/prography/designsystem/component/Store.kt
  core/designsystem/src/main/java/org/prography/designsystem/ui/theme/Theme.kt
  core/designsystem/src/main/res/drawable/bg_img_place_holder.xml
  core/designsystem/src/main/res/drawable/ic_alert.xml
  core/designsystem/src/main/res/drawable/ic_instagram.xml
  core/designsystem/src/main/res/drawable/ic_kakao.xml
  core/designsystem/src/main/res/drawable/ic_website.xml
  core/designsystem/src/main/res/drawable/img_default.xml
  core/designsystem/src/main/res/drawable/img_empty_cakeshop.xml
  core/designsystem/src/main/res/values/strings.xml
  core/network/src/main/java/org/prography/network/api/dto/response/StoreDetailResponse.kt
  domain/src/main/java/org/prography/domain/model/store/StoreDetailModel.kt
  feature/home/build.gradle.kts
  feature/home/src/main/java/org/prography/home/detail/HomeDetailScreen.kt
  gradle/libs.versions.toml
Labels: Done, Design, 원석

#60 [design] 필터 화면 마진 변경
  core/designsystem/src/main/java/org/prography/designsystem/mapper/TypeColor.kt
  core/designsystem/src/main/java/org/prography/designsystem/mapper/TypeIcon.kt
  core/designsystem/src/main/res/values/strings.xml
  domain/src/main/java/org/prography/domain/model/enums/StoreType.kt
  feature/home/src/main/java/org/prography/home/HomeScreen.kt
Labels: Done, Design, 준경
