Repository Prography-8th-team8/Cakk-AOS, pull requests merged in 2023-06, with the labels that each got.

#21 [feat] 홈 화면 바텀시트 개발
  core/designsystem/src/main/java/org/prography/designsystem/ui/theme/Color.kt
  core/designsystem/src/main/res/drawable/ic_line.xml
  core/designsystem/src/main/res/values/strings.xml
  data/src/main/java/org/prography/cakk/data/api/model/response/StoreListResponse.kt
  feature/home/src/main/java/org/prography/home/HomeScreen.kt
Labels: Feature, Done, 준경

#26 [feat] 지역변경 버튼 구현
  core/designsystem/src/main/java/org/prography/designsystem/ui/theme/Color.kt
  core/designsystem/src/main/res/values/strings.xml
  feature/home/src/main/java/org/prography/home/HomeScreen.kt
Labels: Feature, 준경

#28 [feat] 케이크샵 상세 화면 API 연동
  app/src/main/java/org/prography/cakk/navigation/CakkNavigationGraph.kt
  build.gradle.kts
  core/base/src/main/java/org/prography/base/BaseViewModel.kt
  core/designsystem/build.gradle.kts
  core/designsystem/src/main/java/org/prography/designsystem/extensions/Enum.kt
  core/network/build.gradle.kts
  core/network/src/main/java/org/prography/network/CakkService.kt
  core/network/src/main/java/org/prography/network/di/HttpClientModule.kt
  core/utility/src/main/java/org/prography/utility/navigation/destination/CakkDestination.kt
  data/build.gradle.kts
  data/src/main/java/org/prography/cakk/data/api/interceptor/dummy
  data/src/main/java/org/prography/cakk/data/api/model/enums/DistrictType.kt
  data/src/main/java/org/prography/cakk/data/api/model/enums/StoreType.kt
  data/src/main/java/org/prography/cakk/data/api/model/response/StoreDetailResponse.kt
  data/src/main/java/org/prography/cakk/data/api/service/dummy
  data/src/main/java/org/prography/cakk/data/repository/StoreRepository.kt
  data/src/main/java/org/prography/cakk/data/repository/StoreRepositoryImpl.kt
  feature/home/build.gradle.kts
  feature/home/src/main/java/org/prography/home/HomeScreen.kt
  feature/home/src/main/java/org/prography/home/StoreModel.kt
  feature/home/src/main/java/org/prography/home/StoreType.kt
  feature/home/src/main/java/org/prography/home/detail/BlogReviewModel.kt
  feature/home/src/main/java/org/prography/home/detail/HomeDetailAction.kt
  feature/home/src/main/java/org/prography/home/detail/HomeDetailScreen.kt
  feature/home/src/main/java/org/prography/home/detail/HomeDetailSideEffect.kt
  feature/home/src/main/java/org/prography/home/detail/HomeDetailState.kt
  feature/home/src/main/java/org/prography/home/detail/HomeDetailViewModel.kt
  feature/home/src/main/java/org/prography/home/detail/StoreDetailModel.kt
  gradle/libs.versions.toml
Labels: Feature, 원석

#32 [feat] 홈 화면 디자인 수정
  app/src/main/AndroidManifest.xml
  core/designsystem/src/main/res/drawable/ic_swap.xml
  core/designsystem/src/main/res/values/strings.xml
  feature/home/build.gradle.kts
  feature/home/src/main/java/org/prography/home/HomeScreen.kt
  gradle/libs.versions.toml
Labels: Feature, In Progress, 준경

#33 [feat] 홈 지도 화면 MVI 적용 및 관련 로직 수정
  app/src/main/java/org/prography/cakk/navigation/CakkNavigationGraph.kt
  core/utility/src/main/java/org/prography/utility/navigation/destination/CakkDestination.kt
  data/src/main/java/org/prography/cakk/data/api/model/enums/DistrictType.kt
  feature/home/src/main/java/org/prography/home/HomeScreen.kt
  feature/home/src/main/java/org/prography/home/HomeUiAction.kt
  feature/home/src/main/java/org/prography/home/HomeUiSideEffect.kt
  feature/home/src/main/java/org/prography/home/HomeUiState.kt
  feature/home/src/main/java/org/prography/home/HomeViewModel.kt
  feature/home/src/main/java/org/prography/home/StoreModel.kt
  feature/onboarding/src/main/java/org/prography/onboarding/OnBoardingScreen.kt
  feature/splash/src/main/java/org/prography/splash/SplashScreen.kt
Labels: Feature, 원석
