Repository Prography-8th-team8/Cakk-AOS, pull requests merged in 2023-05, with the labels that each got.

#15 [feat] 케이크샵 상세 화면 개발
  core/designsystem/src/main/java/org/prography/designsystem/ui/theme/Color.kt
  core/designsystem/src/main/res/drawable-hdpi/img_default_cakeshop.png
  core/designsystem/src/main/res/drawable-mdpi/img_default_cakeshop.png
  core/designsystem/src/main/res/drawable-xhdpi/img_default_cakeshop.png
  core/designsystem/src/main/res/drawable-xxhdpi/img_default_cakeshop.png
  core/designsystem/src/main/res/drawable-xxxhdpi/img_default_cakeshop.png
  core/designsystem/src/main/res/drawable/ic_bookmark.xml
  core/designsystem/src/main/res/drawable/ic_clock.xml
  core/designsystem/src/main/res/drawable/ic_down_arrow.xml
  core/designsystem/src/main/res/drawable/ic_left_arrow.xml
  core/designsystem/src/main/res/drawable/ic_location.xml
  core/designsystem/src/main/res/drawable/ic_navigation.xml
  core/designsystem/src/main/res/drawable/ic_phone.xml
  core/designsystem/src/main/res/drawable/ic_share.xml
  core/designsystem/src/main/res/values/strings.xml
  feature/home/build.gradle.kts
  feature/home/src/main/java/org/prography/home/BlogReviewModel.kt
  feature/home/src/main/java/org/prography/home/HomeDetailScreen.kt
  feature/home/src/main/java/org/prography/home/StoreModel.kt
  feature/home/src/main/java/org/prography/home/StoreType.kt
Labels: Feature, Done, 원석

#19 [feat] #16 스플래쉬 Lottie 애니메이션 디자인 수정사항에 맞게 구현
  feature/splash/src/main/java/org/prography/splash/SplashScreen.kt
Labels: Design, 원석

#18 [feat] 네트워크 기초 세팅 및 마커 찍기 구현
  .github/workflows/cakk_dev.yml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  build.gradle.kts
  core/base/src/main/java/org/prography/base/BaseAction.kt
  core/base/src/main/java/org/prography/base/BaseSideEffect.kt
  core/base/src/main/java/org/prography/base/BaseState.kt
  core/base/src/main/java/org/prography/base/BaseViewModel.kt
  core/designsystem/src/main/res/drawable/ic_marker.xml
  core/network/build.gradle.kts
  core/network/src/main/java/org/prography/enums/DistrictType.kt
  core/network/src/main/java/org/prography/network/CakkClient.kt
  data/build.gradle.kts
  data/src/main/java/org/prography/cakk/data/api/model/request/StoreListRequest.kt
  data/src/main/java/org/prography/cakk/data/api/model/request/dummy
  data/src/main/java/org/prography/cakk/data/api/model/response/StoreListResponse.kt
  data/src/main/java/org/prography/cakk/data/api/model/response/dummy
  data/src/main/java/org/prography/cakk/data/api/service/dummy
  data/src/main/java/org/prography/cakk/data/di/RepositoryModule.kt
  data/src/main/java/org/prography/cakk/data/di/ServiceModule.kt
  data/src/main/java/org/prography/cakk/data/repository/StoreRepository.kt
  data/src/main/java/org/prography/cakk/data/repository/StoreRepositoryImpl.kt
  data/src/main/java/org/prography/cakk/data/repository/dummy
  feature/home/build.gradle.kts
  feature/home/src/main/java/org/prography/home/HomeScreen.kt
  feature/home/src/main/java/org/prography/home/HomeViewModel.kt
  feature/onboarding/build.gradle.kts
  gradle/libs.versions.toml
Labels: Feature, In Progress, 준경
