Repository Prography-8th-team8/Cakk-AOS, pull requests merged in 2023-08, with the labels that each got.

#52 [feat] 케이크 가게 북마크 기능을 위한 Room 기초 세팅
  core/base/build.gradle.kts
  core/base/consumer-rules.pro
  core/designsystem/build.gradle.kts
  core/designsystem/consumer-rules.pro
  core/localdb/.gitignore
  core/localdb/build.gradle.kts
  core/localdb/proguard-rules.pro
  core/localdb/src/main/AndroidManifest.xml
  core/localdb/src/main/java/org/prography/localdb/dao/BookmarkDao.kt
  core/localdb/src/main/java/org/prography/localdb/database/CakkDatabase.kt
  core/localdb/src/main/java/org/prography/localdb/di/DatabaseModule.kt
  core/localdb/src/main/java/org/prography/localdb/entity/BookmarkEntity.kt
  core/network/build.gradle.kts
  core/network/consumer-rules.pro
  core/utility/build.gradle.kts
  core/utility/consumer-rules.pro
  data/build.gradle.kts
  data/consumer-rules.pro
  data/src/main/java/org/prography/cakk/data/repository/StoreRepositoryImpl.kt
  domain/src/main/java/org/prography/domain/model/store/BookmarkModel.kt
  domain/src/main/java/org/prography/domain/repository/StoreRepository.kt
  feature/home/build.gradle.kts
  feature/home/consumer-rules.pro
  feature/onboarding/build.gradle.kts
  feature/onboarding/consumer-rules.pro
  feature/splash/build.gradle.kts
  feature/splash/consumer-rules.pro
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: Feature, In Progress, 준경

#65 [chore] 깃액션 자바 버전 17로 변경
  .github/workflows/cakk_dev.yml
Labels: Done, 준경, Chore

#63 [chore] DataStore 의존성 추가 및 다른 라이브러리 버전 올리기
  domain/build.gradle.kts
  gradle.properties
  gradle/common.gradle
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
Labels: Done, 준경, Chore

#66 [feat] DataStore 기초세팅
  core/localdb/build.gradle.kts
  core/localdb/src/main/java/org/prography/localdb/di/DatabaseModule.kt
  data/build.gradle.kts
  data/src/main/java/org/prography/cakk/data/datasource/FilterLocalDataSource.kt
  data/src/main/java/org/prography/cakk/data/di/RepositoryModule.kt
  data/src/main/java/org/prography/cakk/data/repository/FilterRepositoryImpl.kt
  domain/src/main/java/org/prography/domain/repository/FilterRepository.kt
Labels: Feature, Done, 준경

#67 [feat] 케이크샵 마커 클릭 시 상세정보 노출 화면 개발
  core/designsystem/src/main/res/drawable/ic_clicked_marker.xml
  feature/home/src/main/java/org/prography/home/HomeScreen.kt
  feature/home/src/main/java/org/prography/home/HomeUiAction.kt
  feature/home/src/main/java/org/prography/home/HomeUiState.kt
  feature/home/src/main/java/org/prography/home/HomeViewModel.kt
  feature/home/src/main/java/org/prography/home/detail/HomeDetailScreen.kt
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
Labels: Feature, Done, 원석

#75 [feat] 케이크샵 리스트에서 키워드 및 사진 정보 없는 케이스 개발
  core/designsystem/src/main/java/org/prography/designsystem/component/Store.kt
  core/designsystem/src/main/res/drawable/img_no_photo.xml
  feature/home/src/main/java/org/prography/home/detail/HomeDetailScreen.kt
Labels: Feature, Done, 원석

#79 [feat] 블로그 리뷰 더보기 버튼 클릭 시 모든 블로그 정보 노출
  core/designsystem/src/main/java/org/prography/designsystem/component/Store.kt
  feature/home/src/main/java/org/prography/home/detail/HomeDetailScreen.kt
Labels: Done, Design, 원석

#85 [design] 마이페이지 디자인
  core/designsystem/src/main/res/drawable/ic_cakk_character.xml
  core/designsystem/src/main/res/values/strings.xml
  feature/my/src/main/java/org/prography/my/MyScreen.kt
Labels: In Progress, Design, 준경

#82 [feat] 피드 구현
  core/designsystem/src/main/java/org/prography/designsystem/component/AppBar.kt
  core/designsystem/src/main/res/values/strings.xml
  core/network/src/main/java/org/prography/network/CakkService.kt
  core/network/src/main/java/org/prography/network/api/dto/response/FeedResponse.kt
  data/build.gradle.kts
  data/src/main/java/org/prography/cakk/data/datasource/FeedPagingSource.kt
  data/src/main/java/org/prography/cakk/data/repository/StoreRepositoryImpl.kt
  domain/build.gradle.kts
  domain/src/main/java/org/prography/domain/model/store/FeedModel.kt
  domain/src/main/java/org/prography/domain/repository/StoreRepository.kt
  feature/feed/build.gradle.kts
  feature/feed/src/main/java/org/prography/feed/FeedScreen.kt
  feature/feed/src/main/java/org/prography/feed/FeedViewModel.kt
  feature/home/src/main/java/org/prography/home/detail/HomeDetailAction.kt
  feature/home/src/main/java/org/prography/home/detail/HomeDetailScreen.kt
  feature/home/src/main/java/org/prography/home/detail/HomeDetailState.kt
  feature/home/src/main/java/org/prography/home/detail/HomeDetailViewModel.kt
  gradle/libs.versions.toml
Labels: Feature, Done, 원석

#83 [feat] 피드 상세 페이지 구현
  app/src/main/java/org/prography/cakk/navigation/CakkNavigationGraph.kt
  common/src/main/java/org/prography/common/navigation/destination/CakkDestination.kt
  core/designsystem/src/main/java/org/prography/designsystem/component/AppBar.kt
  core/designsystem/src/main/res/drawable-hdpi/img_feed_detail.png
  core/designsystem/src/main/res/drawable-mdpi/img_feed_detail.png
  core/designsystem/src/main/res/drawable-xhdpi/img_feed_detail.png
  core/designsystem/src/main/res/drawable-xxhdpi/img_feed_detail.png
  core/designsystem/src/main/res/drawable-xxxhdpi/img_feed_detail.png
  core/designsystem/src/main/res/drawable/ic_chevron_left.xml
  core/designsystem/src/main/res/drawable/ic_chevron_right.xml
  core/designsystem/src/main/res/values/strings.xml
  feature/feed/build.gradle.kts
  feature/feed/src/main/java/org/prography/feed/FeedScreen.kt
  feature/feed/src/main/java/org/prography/feed/detail/FeedDetailAction.kt
  feature/feed/src/main/java/org/prography/feed/detail/FeedDetailScreen.kt
  feature/feed/src/main/java/org/prography/feed/detail/FeedDetailState.kt
  feature/feed/src/main/java/org/prography/feed/detail/FeedDetailViewModel.kt
  gradle/libs.versions.toml
Labels: Feature, Done, 원석

#86 [Design] 공통 팝업 컴포넌트 개발
  core/designsystem/src/main/java/org/prography/designsystem/component/SnackBar.kt
  core/designsystem/src/main/res/values/strings.xml
  feature/home/src/main/java/org/prography/home/HomeScreen.kt
  feature/home/src/main/java/org/prography/home/HomeSideEffect.kt
  feature/home/src/main/java/org/prography/home/HomeViewModel.kt
Labels: Design, 원석

#90 [feat] 케이크 북마크 기능 구현
  core/designsystem/src/main/java/org/prography/designsystem/component/Store.kt
  core/designsystem/src/main/res/drawable/ic_cakk_character.xml
  core/localdb/build.gradle.kts
  core/localdb/src/main/java/org/prography/localdb/converter/ImageListConverters.kt
  core/localdb/src/main/java/org/prography/localdb/dao/BookmarkDao.kt
  core/localdb/src/main/java/org/prography/localdb/database/CakkDatabase.kt
  core/localdb/src/main/java/org/prography/localdb/entity/BookmarkEntity.kt
  data/src/main/java/org/prography/cakk/data/repository/StoreRepositoryImpl.kt
  domain/src/main/java/org/prography/domain/model/store/BookmarkModel.kt
  domain/src/main/java/org/prography/domain/model/store/StoreDetailModel.kt
  domain/src/main/java/org/prography/domain/model/store/StoreModel.kt
  domain/src/main/java/org/prography/domain/repository/StoreRepository.kt
  feature/feed/src/main/java/org/prography/feed/detail/FeedDetailAction.kt
  feature/feed/src/main/java/org/prography/feed/detail/FeedDetailScreen.kt
  feature/feed/src/main/java/org/prography/feed/detail/FeedDetailViewModel.kt
  feature/home/src/main/java/org/prography/home/HomeScreen.kt
  feature/home/src/main/java/org/prography/home/HomeUiAction.kt
  feature/home/src/main/java/org/prography/home/HomeViewModel.kt
  feature/home/src/main/java/org/prography/home/detail/HomeDetailAction.kt
  feature/home/src/main/java/org/prography/home/detail/HomeDetailScreen.kt
  feature/home/src/main/java/org/prography/home/detail/HomeDetailViewModel.kt
  feature/my/src/main/java/org/prography/my/MyScreen.kt
  feature/my/src/main/java/org/prography/my/MyUiAction.kt
  feature/my/src/main/java/org/prography/my/MyUiState.kt
  feature/my/src/main/java/org/prography/my/MyViewModel.kt
  gradle/libs.versions.toml
Labels: Feature, In Progress, 준경

#95 [feat] 가게 필터링 Datastore에 저장하는 로직으로 변경
  core/designsystem/src/main/java/org/prography/designsystem/ui/theme/Color.kt
  core/designsystem/src/main/res/drawable/ic_circle.xml
  core/designsystem/src/main/res/drawable/ic_filter_black.xml
  core/designsystem/src/main/res/values/strings.xml
  data/src/main/java/org/prography/cakk/data/datasource/FilterLocalDataSource.kt
  feature/home/build.gradle.kts
  feature/home/src/main/java/org/prography/home/HomeScreen.kt
  feature/home/src/main/java/org/prography/home/HomeSideEffect.kt
  feature/home/src/main/java/org/prography/home/HomeUiAction.kt
  feature/home/src/main/java/org/prography/home/HomeUiState.kt
  feature/home/src/main/java/org/prography/home/HomeViewModel.kt
  gradle/common.gradle
  gradle/libs.versions.toml
Labels: Feature, In Progress, 준경

#96 [chore] 버전 카탈로그 리펙토링
  app/build.gradle.kts
  build.gradle.kts
  common/build.gradle.kts
  core/base/build.gradle.kts
  core/designsystem/build.gradle.kts
  core/localdb/build.gradle.kts
  core/network/build.gradle.kts
  core/utility/build.gradle.kts
  data/build.gradle.kts
  feature/feed/build.gradle.kts
  feature/home/build.gradle.kts
  feature/my/build.gradle.kts
  feature/onboarding/build.gradle.kts
  feature/splash/build.gradle.kts
  gradle/libs.versions.toml
Labels: In Progress, 준경, Chore

#99 [feat] 블로그 리뷰 더보기 로직 변경
  core/network/src/main/java/org/prography/network/CakkService.kt
  data/src/main/java/org/prography/cakk/data/datasource/StoreRemoteSource.kt
  data/src/main/java/org/prography/cakk/data/repository/StoreRepositoryImpl.kt
  domain/src/main/java/org/prography/domain/repository/StoreRepository.kt
  feature/home/src/main/java/org/prography/home/HomeScreen.kt
  feature/home/src/main/java/org/prography/home/detail/HomeDetailAction.kt
  feature/home/src/main/java/org/prography/home/detail/HomeDetailScreen.kt
  feature/home/src/main/java/org/prography/home/detail/HomeDetailState.kt
  feature/home/src/main/java/org/prography/home/detail/HomeDetailViewModel.kt
Labels: Feature, Done

#101 [bug] 케이크샵 불러오기 버그 수정
  feature/home/src/main/java/org/prography/home/HomeUiAction.kt
  feature/home/src/main/java/org/prography/home/HomeViewModel.kt
Labels: Bug, In Progress, 준경

#103 [feat] 북마크한 케이크 샵 클릭시 디테일로 이동 구현
  app/src/main/java/org/prography/cakk/navigation/CakkNavigationGraph.kt
  feature/my/src/main/java/org/prography/my/MyScreen.kt
Labels: In Progress, 준경, Chore

#108 [chore] 케이크크 앱 업데이트를 위한 변경
  core/designsystem/src/main/res/drawable-hdpi/img_empty_bookmark_cakeshop.png
  core/designsystem/src/main/res/drawable-mdpi/img_empty_bookmark_cakeshop.png
  core/designsystem/src/main/res/drawable-xhdpi/img_empty_bookmark_cakeshop.png
  core/designsystem/src/main/res/drawable-xxhdpi/img_empty_bookmark_cakeshop.png
  core/designsystem/src/main/res/drawable-xxxhdpi/img_empty_bookmark_cakeshop.png
  core/designsystem/src/main/res/drawable/ic_cakk_character.xml
  core/localdb/src/main/java/org/prography/localdb/dao/BookmarkDataSource.kt
  core/localdb/src/main/java/org/prography/localdb/database/CakkDatabase.kt
  core/localdb/src/main/java/org/prography/localdb/di/DatabaseModule.kt
  data/src/main/java/org/prography/cakk/data/datasource/DistrictDataSource.kt
  data/src/main/java/org/prography/cakk/data/datasource/FeedDataSource.kt
  data/src/main/java/org/prography/cakk/data/datasource/FilterDataSource.kt
  data/src/main/java/org/prography/cakk/data/datasource/StoreDataSource.kt
  data/src/main/java/org/prography/cakk/data/repository/DistrictRepositoryImpl.kt
  data/src/main/java/org/prography/cakk/data/repository/FilterRepositoryImpl.kt
  data/src/main/java/org/prography/cakk/data/repository/StoreRepositoryImpl.kt
  feature/feed/src/main/java/org/prography/feed/detail/FeedDetailAction.kt
  feature/home/src/main/java/org/prography/home/HomeUiAction.kt
  feature/home/src/main/java/org/prography/home/HomeViewModel.kt
  feature/home/src/main/java/org/prography/home/detail/HomeDetailAction.kt
  feature/my/src/main/java/org/prography/my/MyScreen.kt
  feature/my/src/main/java/org/prography/my/MyUiAction.kt
  feature/onboarding/src/main/java/org/prography/onboarding/OnBoardingAction.kt
Labels: In Progress, 준경, Chore
